runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /manifest\.json
  static_files: manifest.json
  upload: manifest\.json

- url: /static
  static_dir: static

- url: /static/i
  static_dir: /static/i

- url: /static/js
  static_dir: /static/js

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
